### ISSUE TITLE
Upgrade Unity project to LTS version of Unity editor.

### ISSUE THREAD

**Issue by philgrim2** [doomlab/Migraine-App#31]
In order to eliminate Unity bugs as the cause of several odd behaviors, move to the latest stable Long Term Support version of the Unity editor.

**Comment by doomlab** [comment]
We are going to update the version of unity. Everyone should push their work (@SKirby97 I think you are updated since you emailed me everything, and so @Samual-Bruening can you make sure you've pushed, even if it's not totally working).

@WGrim42 and @philgrim2 are going to update the app and squash all the bugs. They make a new branch and make that default when they have updated/fixed it. We should not do any work during that time, just to make it easier.

Next, you will need to download the new version of Unity. Open the Hub, go to installs click add and you will see this:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/27783894/86628512-fb947980-bf97-11ea-998f-77d7ec402054.png">

It's the first one. Download and then when you use the new branch, we should open in the new version.
